[supervisord]
nodaemon=true
logfile=/dev/null              ; Desativa logs do supervisord
logfile_maxbytes=0             ; Sem rotação de log
logfile_backups=0              ; Sem backups de log
loglevel=error                 ; Nível mínimo de log para reduzir a saída
pidfile=/var/run/supervisord.pid ; Arquivo PID

[supervisorctl]
serverurl=http://127.0.0.1:9001 ; Endpoint para controlar o supervisor

[inet_http_server]
port=127.0.0.1:9001             ; Porta para o servidor HTTP

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[include]
files=supervisord.d/*.conf