#!/usr/bin/env bash

mysql --user=root --password="$MYSQL_ROOT_PASSWORD" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS `$MYSQL_DATABASE` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
    GRANT ALL PRIVILEGES ON \`${MYSQL_DATABASE}%\`.* TO '$MYSQL_USER'@'%';

    GRANT ALL PRIVILEGES
    ON `${MYSQL_DATABASE}`.*
    TO '$MYSQL_USER'@'%'
    WITH GRANT OPTION;

    FLUSH PRIVILEGES;

EOSQL
