[program:projeto-notif]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work --sleep=1 --tries=1 --timeout=3600 --queue=notif_high,notif_default,notif_low
autostart=true
autorestart=true
numprocs=5
startsecs=0
stdout_logfile=/var/www/html/storage/logs/worker_notif.log
stderr_logfile=/var/www/html/storage/logs/worker_notif.error.log
stdout_logfile_backups=0
stderr_logfile_backups=0
stdout_logfile_format=%(asctime)s | %(program_name)s | %(process_num)s | %(message)s
stderr_logfile_format=%(asctime)s | %(program_name)s | %(process_num)s | %(message)s
