[program:laravel-worker-high]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work --sleep=5 --tries=1 --timeout=3600 --queue=high,default,low
autostart=true
autorestart=true
numprocs=2
startsecs=0
stdout_logfile=/var/www/html/storage/logs/worker.log
stderr_logfile=/var/www/html/storage/logs/worker.error.log
stdout_logfile_backups=0
stderr_logfile_backups=0
stdout_logfile_format=%(asctime)s | %(program_name)s | %(process_num)s | %(message)s
stderr_logfile_format=%(asctime)s | %(program_name)s | %(process_num)s | %(message)s

[program:projeto]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work --sleep=5 --tries=1 --timeout=3600 --queue=high,default,low
autostart=true
autorestart=true
numprocs=2
startsecs=0
stdout_logfile=/var/www/html/storage/logs/worker.log
stderr_logfile=/var/www/html/storage/logs/worker.error.log
stdout_logfile_backups=0
stderr_logfile_backups=0
stdout_logfile_format=%(asctime)s | %(program_name)s | %(process_num)s | %(message)s
stderr_logfile_format=%(asctime)s | %(program_name)s | %(process_num)s | %(message)s
